purchasing/config/routes.rb
Purchasing::Application.routes.draw do
  resources :purchase_order_items

  resources :purchase_orders do
    member do
      put 'receive'
    end
  end

end

purchasing/app/models/inventory_item.rb
class InventoryItem
  BASE_URL = "http://localhost:4003/inventory_items.json"

  def self.add_stock(product_id, quantity)
    url = BASE_URL
    response = RestClient.post url, {inventory_item: {product_id: product_id, quantity: quantity}}
  end
end

purchasing/app/models/product.rb
class Product
  BASE_URL = "http://127.0.0.1:4002/products.json"

  def self.all(category_id=nil)
    url = BASE_URL
    url += "?category_id=#{category_id}" if category_id
    JSON.parse(RestClient.get(url))
  end
end

purchasing/app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  attr_accessible :expected_date, :supplier, :status
  has_many :purchase_order_items

  def receive
    purchase_order_items.each do |item|
      item.receive
    end
    self.update_attributes!(status: 'received')
  end
end

purchasing/app/models/purchase_order_item.rb
class PurchaseOrderItem < ActiveRecord::Base
  attr_accessible :price, :product_id, :purchase_order_id, :quantity
  belongs_to :purchase_order

  def receive
    InventoryItem.add_stock(product_id, quantity)
  end
end

purchasing/app/controllers/purchase_order_items_controller.rb
class PurchaseOrderItemsController < ApplicationController
  # GET /purchase_order_items
  # GET /purchase_order_items.json
  def index
    @purchase_order_items = PurchaseOrderItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchase_order_items }
    end
  end

  # GET /purchase_order_items/1
  # GET /purchase_order_items/1.json
  def show
    @purchase_order_item = PurchaseOrderItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchase_order_item }
    end
  end

  # GET /purchase_order_items/new
  # GET /purchase_order_items/new.json
  def new
    @purchase_order_item = PurchaseOrderItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchase_order_item }
    end
  end

  # GET /purchase_order_items/1/edit
  def edit
    @purchase_order_item = PurchaseOrderItem.find(params[:id])
  end

  # POST /purchase_order_items
  # POST /purchase_order_items.json
  def create
    @purchase_order_item = PurchaseOrderItem.new(params[:purchase_order_item])

    respond_to do |format|
      if @purchase_order_item.save
        format.html { redirect_to @purchase_order_item, notice: 'Purchase order item was successfully created.' }
        format.json { render json: @purchase_order_item, status: :created, location: @purchase_order_item }
      else
        format.html { render action: "new" }
        format.json { render json: @purchase_order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purchase_order_items/1
  # PUT /purchase_order_items/1.json
  def update
    @purchase_order_item = PurchaseOrderItem.find(params[:id])

    respond_to do |format|
      if @purchase_order_item.update_attributes(params[:purchase_order_item])
        format.html { redirect_to @purchase_order_item, notice: 'Purchase order item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchase_order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_order_items/1
  # DELETE /purchase_order_items/1.json
  def destroy
    @purchase_order_item = PurchaseOrderItem.find(params[:id])
    @purchase_order_item.destroy

    respond_to do |format|
      format.html { redirect_to purchase_order_items_url }
      format.json { head :no_content }
    end
  end
end

purchasing/app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  # GET /purchase_orders
  # GET /purchase_orders.json
  def index
    @purchase_orders = PurchaseOrder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchase_orders }
    end
  end

  # GET /purchase_orders/1
  # GET /purchase_orders/1.json
  def show
    @purchase_order = PurchaseOrder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchase_order }
    end
  end

  # GET /purchase_orders/new
  # GET /purchase_orders/new.json
  def new
    @purchase_order = PurchaseOrder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchase_order }
    end
  end

  # GET /purchase_orders/1/edit
  def edit
    @purchase_order = PurchaseOrder.find(params[:id])
  end

  # POST /purchase_orders
  # POST /purchase_orders.json
  def create
    @purchase_order = PurchaseOrder.new(params[:purchase_order].merge(status: 'created'))

    respond_to do |format|
      if @purchase_order.save
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully created.' }
        format.json { render json: @purchase_order, status: :created, location: @purchase_order }
      else
        format.html { render action: "new" }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purchase_orders/1
  # PUT /purchase_orders/1.json
  def update
    @purchase_order = PurchaseOrder.find(params[:id])

    respond_to do |format|
      if @purchase_order.update_attributes(params[:purchase_order])
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def receive
    @purchase_order = PurchaseOrder.find(params[:id])
    @purchase_order.receive
    redirect_to purchase_orders_path
  end

  # DELETE /purchase_orders/1
  # DELETE /purchase_orders/1.json
  def destroy
    @purchase_order = PurchaseOrder.find(params[:id])
    @purchase_order.destroy

    respond_to do |format|
      format.html { redirect_to purchase_orders_url }
      format.json { head :no_content }
    end
  end
end

purchasing/app/helpers/purchase_order_items_helper.rb
module PurchaseOrderItemsHelper
end

purchasing/app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

purchasing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Purchasing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

purchasing/app/views/purchase_orders/_form.html.erb
<%= form_for(@purchase_order) do |f| %>
  <% if @purchase_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase_order.errors.count, "error") %> prohibited this purchase_order from being saved:</h2>

      <ul>
      <% @purchase_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :supplier %><br />
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :expected_date %><br />
    <%= f.datetime_select :expected_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

purchasing/app/views/purchase_orders/edit.html.erb
<h1>Editing purchase_order</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase_order %> |
<%= link_to 'Back', purchase_orders_path %>

purchasing/app/views/purchase_orders/index.html.erb
<h1>Listing purchase_orders</h1>

<table>
  <tr>
    <th>Supplier</th>
    <th>Expected date</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @purchase_orders.each do |purchase_order| %>
  <tr>
    <td><%= purchase_order.supplier %></td>
    <td><%= purchase_order.expected_date %></td>
    <td><%= purchase_order.status %></td>
    <td><%= link_to 'Show', purchase_order %></td>
    <td><%= link_to 'Edit', edit_purchase_order_path(purchase_order) %></td>
    <td><%= link_to 'Destroy', purchase_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Purchase order', new_purchase_order_path %>

purchasing/app/views/purchase_orders/new.html.erb
<h1>New purchase_order</h1>

<%= render 'form' %>

<%= link_to 'Back', purchase_orders_path %>

purchasing/app/views/purchase_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <span id='purchase-order-id'><%= @purchase_order.id %></span>
</p>

<p>
  <b>Supplier:</b>
  <%= @purchase_order.supplier %>
</p>

<p>
  <b>Expected date:</b>
  <%= @purchase_order.expected_date %>
</p>

<p>
  <b>Status:</b>
  <%= @purchase_order.status %>
</p>

<%= button_to 'Receive Items', receive_purchase_order_path, method: 'put'%>

<p>
<%= link_to 'Edit', edit_purchase_order_path(@purchase_order) %> |
<%= link_to 'Back', purchase_orders_path %>
</p>