shipping/config/routes.rb
Shipping::Application.routes.draw do
  resources :delivery_items

end

shipping/app/models/delivery_item.rb
class DeliveryItem < ActiveRecord::Base
  attr_accessible :product_id, :quantity, :shipping_address
end

shipping/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

shipping/app/controllers/delivery_items_controller.rb
class DeliveryItemsController < ApplicationController
  # GET /delivery_items
  # GET /delivery_items.json
  def index
    @delivery_items = DeliveryItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @delivery_items }
    end
  end

  # GET /delivery_items/1
  # GET /delivery_items/1.json
  def show
    @delivery_item = DeliveryItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @delivery_item }
    end
  end

  # GET /delivery_items/new
  # GET /delivery_items/new.json
  def new
    @delivery_item = DeliveryItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @delivery_item }
    end
  end

  # GET /delivery_items/1/edit
  def edit
    @delivery_item = DeliveryItem.find(params[:id])
  end

  # POST /delivery_items
  # POST /delivery_items.json
  def create
    @delivery_item = DeliveryItem.new(params[:delivery_item])

    respond_to do |format|
      if @delivery_item.save
        format.html { redirect_to @delivery_item, notice: 'Delivery item was successfully created.' }
        format.json { render json: @delivery_item, status: :created, location: @delivery_item }
      else
        format.html { render action: "new" }
        format.json { render json: @delivery_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /delivery_items/1
  # PUT /delivery_items/1.json
  def update
    @delivery_item = DeliveryItem.find(params[:id])

    respond_to do |format|
      if @delivery_item.update_attributes(params[:delivery_item])
        format.html { redirect_to @delivery_item, notice: 'Delivery item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @delivery_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivery_items/1
  # DELETE /delivery_items/1.json
  def destroy
    @delivery_item = DeliveryItem.find(params[:id])
    @delivery_item.destroy

    respond_to do |format|
      format.html { redirect_to delivery_items_url }
      format.json { head :no_content }
    end
  end
end

shipping/app/helpers/application_helper.rb
module ApplicationHelper
end

shipping/app/helpers/delivery_items_helper.rb
module DeliveryItemsHelper
end

shipping/app/views/delivery_items/_form.html.erb
<%= form_for(@delivery_item) do |f| %>
  <% if @delivery_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delivery_item.errors.count, "error") %> prohibited this delivery_item from being saved:</h2>

      <ul>
      <% @delivery_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :shipping_address %><br />
    <%= f.text_field :shipping_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

shipping/app/views/delivery_items/edit.html.erb
<h1>Editing delivery_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @delivery_item %> |
<%= link_to 'Back', delivery_items_path %>

shipping/app/views/delivery_items/index.html.erb
<h1>Listing delivery_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Shipping address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @delivery_items.each do |delivery_item| %>
  <tr>
    <td><%= delivery_item.product_id %></td>
    <td><%= delivery_item.quantity %></td>
    <td><%= delivery_item.shipping_address %></td>
    <td><%= link_to 'Show', delivery_item %></td>
    <td><%= link_to 'Edit', edit_delivery_item_path(delivery_item) %></td>
    <td><%= link_to 'Destroy', delivery_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Delivery item', new_delivery_item_path %>

shipping/app/views/delivery_items/new.html.erb
<h1>New delivery_item</h1>

<%= render 'form' %>

<%= link_to 'Back', delivery_items_path %>

shipping/app/views/delivery_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @delivery_item.product_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @delivery_item.quantity %>
</p>

<p>
  <b>Shipping address:</b>
  <%= @delivery_item.shipping_address %>
</p>


<%= link_to 'Edit', edit_delivery_item_path(@delivery_item) %> |
<%= link_to 'Back', delivery_items_path %>

shipping/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shipping</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>