store/config/routes.rb
Store::Application.routes.draw do
  post "home/login"

  post "home/logout"

  resources :users
  resources :products, only: [:index, :show]
  match 'products/:product_id/add_to_cart' => 'products#add_to_cart', as: :add_to_cart
  
  resources :carts, only: [:show]
  resources :orders, only: [:create, :show, :index] do
    member do
      post 'fulfill'
    end
  end

  root :to => 'products#index'

end

store/app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :user_id
  has_many :cart_items
  belongs_to :user

  def add_item(product_id)
    cart_item = self.cart_items.find_or_create_by_product_id(product_id)
    quantity = (cart_item.quantity || 0) + 1
    cart_item.update_attributes!(quantity: quantity)
  end

  def create_order
    products_by_id = Product.all.index_by {|p| p['id']}
    order = Order.create!(user_id: user_id, status: 'created')
    cart_items.each do |cart_item|
      price = products_by_id[cart_item.product_id]['price']
      order.order_items.create!(product_id: cart_item.product_id, quantity: cart_item.quantity, price: price, status: 'created')
      cart_item.destroy
    end
    order
  end
end

store/app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id, :quantity
  belongs_to :cart
end

store/app/models/category.rb
# require 'restclient'

class Category
  BASE_URL = "http://127.0.0.1:4002/categories.json"

  def self.all
    JSON.parse(RestClient.get(BASE_URL))
  end
end

store/app/models/inventory_item.rb
class InventoryItem
  BASE_URL = "http://localhost:4003"

  def self.fulfill(product_id, quantity, shipping_address)
    url = "#{BASE_URL}/inventory_items/fulfill.json"
    response = RestClient.post url, {product_id: product_id, quantity: quantity, shipping_address: shipping_address}
  end
end

store/app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :user_id, :status
  has_many :order_items
  belongs_to :user

  def fulfill
    order_items.each do |order_item|
      InventoryItem.fulfill(order_item.product_id, order_item.quantity, self.user.shipping_address || "PO-BOX-123")
    end
    self.update_attributes!(status: 'fulfilled')
  end
end

store/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  attr_accessible :order_id, :price, :product_id, :quantity, :status
  belongs_to :order
end

store/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :mobile, :password, :username
end

store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    session[:user_id] ||= "guest#{rand(1000)}"
    User.find_or_create_by_username(session[:user_id])
  end
end

store/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find(params[:id])
    @products_by_id = Product.all.index_by{|p| p['id']}
  end
end

store/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def login:post
  end

  def logout:post
  end
end

store/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @cart = Cart.find_by_user_id(current_user.id)
    order = @cart.create_order
    redirect_to order_path(order.id)
  end

  def show
    @order = Order.find(params[:id])
    @products_by_id = Product.all.index_by {|p| p['id']}
  end

  def index
    @orders = Order
    @orders = @orders.where(status: params[:status]) unless params[:status].blank?
    @orders = @orders.all
  end

  def fulfill
    @order = Order.find(params[:id])
    @order.fulfill
    redirect_to orders_path
  end
end

store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @cart = user_cart
    @categories = Category.all
    category_id = params[:category_id]
    @products = Product.all(category_id)
  end

  def add_to_cart
    @cart = user_cart
    @cart.add_item(params[:product_id])
    redirect_to(@cart)
  end

  private

  def user_cart
    Cart.find_or_create_by_user_id(current_user.id)
  end
end

store/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

store/app/helpers/carts_helper.rb
module CartsHelper
end

store/app/helpers/home_helper.rb
module HomeHelper
end

store/app/helpers/orders_helper.rb
module OrdersHelper
end

store/app/helpers/products_helper.rb
module ProductsHelper
end

store/app/helpers/users_helper.rb
module UsersHelper
end

store/app/views/home/login:post.html.erb
<h1>Home#login:post</h1>
<p>Find me in app/views/home/login:post.html.erb</p>

store/app/views/home/logout:post.html.erb
<h1>Home#logout:post</h1>
<p>Find me in app/views/home/logout:post.html.erb</p>

store/app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

store/app/views/orders/index.html.erb
<h2>
  <%= image_tag 'ecart.jpg', width: 50, height: 50%>
  EStore
</h2>
<h3>Order status</h3>
<p>
<span><%=link_to 'All', orders_path %></span> |
<span><%=link_to 'New', orders_path(status: 'created') %></span> |
<span><%=link_to 'Fulfilled', orders_path(status: 'fulfilled') %></span> |
</p>
<table border='0'>
  <tr>
    <th>Order ID</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td>
      <%= link_to "ESO#{order.id}", order_path(order.id) %>
    </td>
    <td>
      <%= order.status %>
    </td>
    <td>
      <div class='order-actions'>
        <% if order.status == 'created' %>
          <%= button_to 'Fulfill', fulfill_order_path(order.id), id: "fulfill-order-#{order.id}" %>
        <% end %>
      </div>
    </td>
  </tr>
<% end %>
</table>

store/app/views/orders/show.html.erb
<h2>
  <%= image_tag 'ecart.jpg', width: 50, height: 50%>
  EStore
</h2>
<div class='order-links'>
  <%= link_to 'Continue shopping', products_path %> | 
  <%= link_to 'View Cart', @cart %>
</div>
<h3>Order # ESO<%=@order.id%></h3>
<input type="hidden" id="order-id" value="<%=@order.id%>"/>
<p>Status: <em><%=@order.status%></em></p>
<input type="hidden" id="order-status" value="<%=@order.status%>"/>
<% total_price = 0.0 %>
<% @order.order_items.each do |order_item| %>
  <%
    product = @products_by_id[order_item.product_id]
    price = order_item.quantity * order_item.price
    total_price += price
  %>
  <div class="cart-item-#{cart_item.product_id}">
    <%= order_item.quantity %>
    x
    <%= product['title'] %>
    =
    <%= price %>
  </div>
<% end %>
Total: <%= total_price %>

store/app/views/products/add_to_cart:post.html.erb
<h1>Products#add_to_cart:post</h1>
<p>Find me in app/views/products/add_to_cart:post.html.erb</p>

store/app/views/products/index.html.erb
<h2>
  <%= image_tag 'ecart.jpg', width: 50, height: 50%>
  EStore
</h2>
<div class='category-select'>
  <p>
  <span>
    <%= link_to 'All', products_path %> | 
  </span>
  <% @categories.each do |category|%>
    <%= link_to category['name'], products_path(category_id: category['id']) %> | 
  <% end %>
  <p>
</div>
<div class='order-links'>
  <%= link_to 'View Cart', @cart %>
</div>
<% @products.each do |product|%>
  <div class='product' id="product-#{product['id']}">
    <h4>
      <%=product['title']%>
    </h4>
    <span>
      <%= image_tag product['image_url'] %>
    </span>
    <p>
      <%=product['description']%>
    </p>
    <%= button_to 'Add to Cart', add_to_cart_path(product['id']), class: 'add-to-cart', id: "add-to-cart-#{product['id']}" %>
  </div>
<% end %>

store/app/views/products/index:get.html.erb
<h1>Products#index:get</h1>
<p>Find me in app/views/products/index:get.html.erb</p>

store/app/views/products/show:get.html.erb
<h1>Products#show:get</h1>
<p>Find me in app/views/products/show:get.html.erb</p>